- name: log in using aws credentials and pull docker image
  hosts: all
  gather_facts: false
  tasks:
    - name: setup awscli
      become: yes
      apt:
        name: awscli
    - name: install python docker module
      pip:
        name: docker
    - name: docker login to ecr
      shell: 
        cmd: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 804064231264.dkr.ecr.us-east-1.amazonaws.com
    - name: pull docker image
      docker_image:
        name: 804064231264.dkr.ecr.us-east-1.amazonaws.com/hello-world-flask-app:latest
